### ISSUE TITLE
[BUG] client build fails with node 17

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/single-cell-explorer#227]
Builds with node 17 fail (error below).  Verified on Linux/Node 17.4.0.

The build _works_ on node 16.

To reproduce: `make dev-env-server build-for-server-dev` 

Error:
```
(node:864021) [DEP_WEBPACK_COMPILATION_OPTIMIZE_CHUNK_ASSETS] DeprecationWarning: optimizeChunkAssets is deprecated (use Compilation.hooks.processAssets instead and use one of Compilation.PROCESS_ASSETS_STAGE_* as stage option)
(Use `node --trace-deprecation ...` to show where the warning was created)
node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at BulkUpdateDecorator.hashFactory (/home/bruce/projects/single-cell-explorer/client/node_modules/webpack/lib/util/createHash.js:145:18)
    at BulkUpdateDecorator.update (/home/bruce/projects/single-cell-explorer/client/node_modules/webpack/lib/util/createHash.js:46:50)
    at SourceMapSource.updateHash (/home/bruce/projects/single-cell-explorer/client/node_modules/webpack/node_modules/webpack-sources/lib/SourceMapSource.js:226:8)
    at NormalModule._initBuildHash (/home/bruce/projects/single-cell-explorer/client/node_modules/webpack/lib/NormalModule.js:870:17)
    at handleParseResult (/home/bruce/projects/single-cell-explorer/client/node_modules/webpack/lib/NormalModule.js:936:10)
    at /home/bruce/projects/single-cell-explorer/client/node_modules/webpack/lib/NormalModule.js:1028:4
    at processResult (/home/bruce/projects/single-cell-explorer/client/node_modules/webpack/lib/NormalModule.js:745:11)
    at /home/bruce/projects/single-cell-explorer/client/node_modules/webpack/lib/NormalModule.js:809:5 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.4.0
make[1]: *** [Makefile:23: build] Error 1
make[1]: Leaving directory '/home/bruce/projects/single-cell-explorer/client'
make: *** [Makefile:31: build-client] Error 2
```

**Comment by tihuan** [comment]
Possible temp solution:

https://github.com/webpack/webpack/issues/14532#issuecomment-1021335691

**Comment by tihuan** [comment]
Closing this for now, since node 16 works
