### ISSUE TITLE
bug(dataset-metadata): failing to retrieve dataset metadata for revision.

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/single-cell-explorer#575]
**Describe the bug**
failing to retrieve dataset metadata for revision for an uploaded dataset. This is likely any issue with data portal.

```
  | 2023-03-21T22:34:45.555Z | Traceback (most recent call last):
-- | -- | --
  | 2023-03-21T22:34:45.555Z | File "/server/dataset/dataset_metadata.py", line 123, in get_dataset_and_collection_metadata
  | 2023-03-21T22:34:45.555Z | "dataset_name": [dataset["name"] for dataset in res["datasets"] if dataset["id"] == dataset_id][0],
  | 2023-03-21T22:34:45.555Z | IndexError: list index out of range
  | 2023-03-21T22:34:45.555Z | The above exception was the direct cause of the following exception:
  | 2023-03-21T22:34:45.555Z | Traceback (most recent call last):
  | 2023-03-21T22:34:45.555Z | File "/server/app/api/v3.py", line 159, in wrapped_function
  | 2023-03-21T22:34:45.555Z | return func(self, data_adaptor)
  | 2023-03-21T22:34:45.555Z | File "/server/app/api/v3.py", line 177, in get
  | 2023-03-21T22:34:45.555Z | return common_rest.dataset_metadata_get(current_app.app_config, self.url_dataroot, data_adaptor.dataset_id)
  | 2023-03-21T22:34:45.555Z | File "/server/common/rest.py", line 121, in dataset_metadata_get
  | 2023-03-21T22:34:45.555Z | metadata = dataset_metadata.get_dataset_and_collection_metadata(url_dataroot, dataset_id, app_config)
  | 2023-03-21T22:34:45.555Z | File "/server/dataset/dataset_metadata.py", line 140, in get_dataset_and_collection_metadata
  | 2023-03-21T22:34:45.555Z | raise DatasetMetadataError("Error retrieving dataset metadata") from ex
  | 2023-03-21T22:34:45.555Z | server.common.errors.DatasetMetadataError: Error retrieving dataset metadata
[2023-03-21 22:34:45,555] INFO in app: {
    "status_code": 400,
    "content_length": 92,
    "url": "/cellxgene/e/ac2fea99-ce08-4fca-8d03-a19f37bf21a3.cxg/api/v0.3/dataset-metadata",
    "method": "GET",
    "schema": "http"
}
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version (please complete the following information):**
 - Version: https://github.com/chanzuckerberg/single-cell-explorer/commit/7c458fc7c5bf34dffbc2b53d0599796032a70f07

**Additional context**
[original conversation](https://czi-sci.slack.com/archives/C024HCSH9PT/p1679438983162419)
maybe related https://czi-sci.slack.com/archives/C024HCSH9PT/p1679438983162419

**Comment by Bento007** [comment]
Closing for https://github.com/chanzuckerberg/single-cell-data-portal/issues/4390
